export const MINITICKER_WS_INIT = 'MINITICKER_WS_INIT';
export const MINITICKER_WS_LOADING = 'MINITICKER_WS_LOADING';
export const MINITICKER_WS_OPEN = 'MINITICKER_WS_OPEN';
export const MINITICKER_WS_ERROR = 'MINITICKER_WS_ERROR';
export const MINITICKER_WS_MESSAGE = 'MINITICKER_WS_MESSAGE';
export const MINITICKER_WS_CLOSE = 'MINITICKER_WS_CLOSE';