export const ORDERBOOK_WS_INIT = 'ORDERBOOK_WS_INIT';
export const ORDERBOOK_WS_LOADING = 'ORDERBOOK_WS_LOADING';
export const ORDERBOOK_WS_OPEN = 'ORDERBOOK_WS_OPEN';
export const ORDERBOOK_WS_ERROR = 'ORDERBOOK_WS_ERROR';
export const ORDERBOOK_WS_MESSAGE = 'ORDERBOOK_WS_MESSAGE';
export const ORDERBOOK_WS_CLOSE = 'ORDERBOOK_WS_CLOSE';
