export const TICKER_WS_INIT = 'TICKER_WS_INIT';
export const TICKER_WS_LOADING = 'TICKER_WS_LOADING';
export const TICKER_WS_OPEN = 'TICKER_WS_OPEN';
export const TICKER_WS_ERROR = 'TICKER_WS_ERROR';
export const TICKER_WS_MESSAGE = 'TICKER_WS_MESSAGE';
export const TICKER_WS_CLOSE = 'TICKER_WS_CLOSE';
