export const TRADES_WS_INIT = 'TRADES_WS_INIT';
export const TRADES_WS_LOADING = 'TRADES_WS_LOADING';
export const TRADES_WS_OPEN = 'TRADES_WS_OPEN';
export const TRADES_WS_ERROR = 'TRADES_WS_ERROR';
export const TRADES_WS_MESSAGE = 'TRADES_WS_MESSAGE';
export const TRADES_WS_CLOSE = 'TRADES_WS_CLOSE';